name: Chainloop Keyless Attestation

on:
  push:
    branches: [main]
  pull_request:

jobs:
  attest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      CHAINLOOP_PLATFORM_API: https://cl-backend.ngrok.app
      CHAINLOOP_CONTROL_PLANE_API: brittni-suasory-josephina.ngrok-free.dev:443
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Chainloop CLI
        run: curl -sfL https://dl.chainloop.dev/cli/install.sh | bash -s -- -ee
      - name: Init attestation (keyless)
        run: |
          chainloop att init \
            --project matiasproject \
            --workflow matiasworkflow

      - name: Dummy wait
        run: sleep 420

      - name: Push attestation
        run: chainloop attestation push
